import { audioFiles } from "./audioData.js";

const gameData = [
    // Parte 1 - Quarto
    {
        black_screen_transition: false,
        speaker: "Piter",
        text: "MEU DEUS JÁ SÃO 6 HORAS",
        img_character1: "",
        img_character2: "",
        background: "../img/piter-waking.png",
        audio: audioFiles.piter_irritado,
        thereIsQuestion: false,
    },
    {
        black_screen_transition: false,
        speaker: "Piter",
        text: "Ta na hora de levantar! Hoje eu tenho prova de lógica de programação, não posso me atrasar de maneira alguma.",
        img_character1: "",
        img_character2: "",
        background: "../img/piter-waking.png",
        audio: "",
        thereIsQuestion: false,
    },
    {
        black_screen_transition: false,
        speaker: "Piter",
        text: "E falando em prova, não estudei quase nada... Que que eu faço agora.",
        img_character1: "",
        img_character2: "",
        background: "../img/piter-waking.png",
        audio: "",
        thereIsQuestion: false,
    },
    {
        black_screen_transition: false,
        speaker: "Piter",
        text: "E se eu...",
        img_character1: "",
        img_character2: "",
        background: "../img/piter-waking.png",
        audio: "",
        thereIsQuestion: false,
    },
    {
        black_screen_transition: false,
        speaker: "Piter",
        text: "Já sei, vou estudando para prova conforme eu vou indo pra faculdade!",
        img_character1: "",
        img_character2: "",
        background: "../img/piter-waking.png",
        audio: audioFiles.piter_feliz,
        thereIsQuestion: false,
    },
    {
        black_screen_transition: false,
        speaker: "Piter",
        text: "Assim vou treinando minha lógica de programação pra ir com a cabeça fresca pra prova!",
        img_character1: "",
        img_character2: "",
        background: "../img/piter-waking.png",
        audio: "",
        thereIsQuestion: false,
    },
    {
        black_screen_transition: false,
        speaker: "Piter",
        text: "Vou tomar um banho pra ver se eu acordo, preciso estar 100% acordado para fazer essa prova.",
        img_character1: "",
        img_character2: "",
        background: "../img/piter-waking.png",
        audio: "",
        thereIsQuestion: false,
    },
    // Parte 2 - Banheiro
    {
        black_screen_transition: true,
        speaker: "Piter",
        text: "... Cara o que vai cair na prova mesmo?",
        img_character1: "",
        img_character2: "",
        background: "../img/piter-shower.png",
        audio: audioFiles.porta,
        thereIsQuestion: false,
    },
    {
        black_screen_transition: false,
        speaker: "Piter",
        text: "Estruturas condicionais... Laços de repetições... Filas e Pilha.",
        img_character1: "",
        img_character2: "",
        background: "../img/piter-shower.png",
        audio: "",
        thereIsQuestion: false,
    },
    {
        black_screen_transition: false,
        speaker: "Piter",
        text: "É, acho que é só isso mesmo.",
        img_character1: "",
        img_character2: "",
        background: "../img/piter-shower.png",
        audio: "",
        thereIsQuestion: false,
    },
    {
        black_screen_transition: false,
        speaker: "Piter",
        text: "Ta, como eu posso pensar na utilização de uma <b>estrutura condicional</b> para tomar banho?",
        img_character1: "",
        img_character2: "",
        background: "../img/piter-shower.png",
        audio: "",
        thereIsQuestion: true,
    },
    {
        black_screen_transition: false,
        speaker: "Piter",
        text: "Falando em banho, bora-la!",
        img_character1: "",
        img_character2: "",
        background: "../img/piter-shower.png",
        audio: audioFiles,
        thereIsQuestion: false,
    },
    {
        black_screen_transition: true,
        speaker: "Piter",
        text: "Certo, to de banho tomado.",
        img_character1: "",
        img_character2: "",
        background: "../img/piter-shower.png",
        audio: audioFiles.shower,
        thereIsQuestion: false,
    },
    {
        black_screen_transition: false,
        speaker: "Piter",
        text: "Acho que agora vou ir tomar um café da manhã para ter energia para pensar na hora da prova.",
        img_character1: "",
        img_character2: "",
        background: "../img/piter-shower.png",
        audio: "",
        thereIsQuestion: false,
    },
];

export { gameData };